version: '3.9'

networks:
  gateway:
    driver: bridge
services:
  consul:
    image: consul
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - gateway
      
  service-a:
    image: service_a:latest
    build:
      context: .
      dockerfile: ApiServiceA/Dockerfile
    container_name: service-a
    ports:
      - 5101:5101
    depends_on:
      - consul
    networks:
      - gateway

  service-b:
    image: service_b:latest
    build:
      context: .
      dockerfile: ApiServiceB/Dockerfile
    container_name: service-b
    ports:
      - 5102:5102
    depends_on:
      - consul
    networks:
      - gateway

  gateway-app:
    image: gateway-app:latest
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    container_name: gateway-app
    ports:
      - 5100:5100
    depends_on:
      - service-a
      - service-b
    networks:
      - gateway  